### ISSUE TITLE
Download Buttons Cover Up Notifications

### ISSUE THREAD

**Issue by macitpros** [sphen13/BlueSky#17]
Noticed this after deleting a computer record during testing. Maybe moving the Download buttons down to the footer area would be the easiest fix?

![screenshot_412](https://user-images.githubusercontent.com/17754199/44547324-54c6cd00-a6e0-11e8-9168-7027ca57e3cd.png)

**Comment by sphen13** [comment]
Yep will take care of this eventually :) the appgini framework is difficult.

On Aug 23, 2018, at 3:25 PM, Dan Monge <notifications@github.com<mailto:notifications@github.com>> wrote:


Noticed this after deleting a computer record during testing. Maybe moving the Download buttons down to the footer area would be the easiest fix?

[screenshot_412]<https://user-images.githubusercontent.com/17754199/44547324-54c6cd00-a6e0-11e8-9168-7027ca57e3cd.png>

**Comment by sphen13** [comment]
resolved in 2.3 branch
